# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0002_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
