# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0003_auto_20190802_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avator',
            field=models.ImageField(default='avator/default.png', upload_to='avator/', verbose_name='用户头像'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='cz@qq.com', max_length=254, verbose_name='邮箱'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='english_score',
            field=models.FloatField(default='5.5', verbose_name='英语成绩'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_login',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_login2',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='student',
            name='last_login_ip',
            field=models.GenericIPAddressField(default='1.2.3.4', verbose_name='最后登录IP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='schooling',
            field=models.DecimalField(decimal_places=2, default='450', max_digits=7, verbose_name='学费'),
            preserve_default=False,
        ),
    ]
